services:
  postgres:
    container_name: postgres_currency_exchanger
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=currency-exchanger'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    volumes:
      - currency-exchanger-data:/var/lib/postgresql/data
    ports:
      - '5555:5432'

volumes:
  currency-exchanger-data: